language: 
    - cpp
    - python
python:
    - "3.6"
os: linux

# Install necessary packages
before_install:

    - python --version

    - pip list

install:
  - pip install -r requirements.txt
script:
  — python pytest
