# Set up environment
matrix:
  include:
  - language: cpp
  - language: python
    python: 3.6
os: linux
before_install:
  - python3 --version
install:
  - pip install -r requirements.txt
script:
  — pytest
