on: [push, pull_request]
jobs:
  GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3
      - name: Python Linter
        uses: sunnysid3up/python-linter@v0.1-beta.7

