name: all-lints

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: PyAction: One-stop Python linter
        uses: actions/checkout@v1
        uses: rahul-deepsource/pyaction@master
